### ISSUE TITLE
Divvun proofing tools crashing MS Office badly

### ISSUE THREAD

**Issue by snomos** [divvun/windivvun-service#1]
We have received the following bug report from an institutional user:

> an employee installed North Sami Divvun today, and it basically made all Office programs crash. After installation, space and all punctuation marks (;,.=?) stopped working in all Office-based programs. For example, all messages on Skype have to be written without spaces or punctuation. Removing Divvun or restarting did not fix the problem. We're now trying to fix the problem by re-installing  Office programs. Just thought you should know. 

It is probably Windows, I will ask for more details. Move the issue to the correct repo if this is wrong.

**Comment by snomos** [comment]
More info from the user:

> So, I downloaded and ran the installer which can be found from [http://divvun.no/fi/](http://divvun.no/fi/) and the file was **divvun-installer-1.0.1.exe**. I can’t exactly remember what parts of the program I installed (I left out Libre versions and those Sámi languages which are not spoken in Finland, excluding Southern Sámi).
>  
> This is the 64-bit Windows version I used:
>  
> ![image](https://user-images.githubusercontent.com/1255285/82478343-79c8b980-9ad9-11ea-984f-489a420fa214.png)
> 
>  
> The Office version I checked from Word settings is **MSO Professional Plus (16.0.4266.1001) 64-bit**.
>  
> After I had installed Divvun and restarted my computer the problems began. Word and Outlook crashed few seconds after opening them. Skype worked until I tried to use ,.;:-_?! (etc.) or space, which caused it to crash. I could use normal letters and đŋáŧčž etc.
>  
> I tried a few ways to solve the problem but none worked. Changing the input language or keyboard of Windows; re-installing Office; deleting all Divvun files from Programs Files and cleaning registeries with CCleaner did not help. Eventually I had to re-install Windows.
>  
> I suppose all the program versions are same that my PC had before I re-installed Windows, as this PC had it’s Windows re-installed just last week, before I started at this job.
>  
> I’m not an IT expert, so I hope I answered your questions satisfyingly.
>  
> I hope this clears things. Right now I don’t want to try installing the program again on this computer. x) (But it works just fine on my home computers!)

Note the last comment - the user has positive experience on another machine, so this problem is specific to the setup reported.

**Comment by snomos** [comment]
Info about other software on the computer, in case there are bad interactions going on:

> These work computers only have Check Point Software’s VPN and Novell Client / Client for Open Enterprise Server as additional softwares. Anti-Virus is F-Secure Client Security Premium.

**Comment by snomos** [comment]
Same issue as reported by @albbas in Snåsa. Turns out it is an old version of MS Office (last updated in 2015) that we presently do not support. Our bug is that we allowed our tools to be installed on unsupported versions in the first place. We need to add a version check that only allows our tools to be installed on supported systems.

**Comment by albbas** [comment]
The reason for the crash is the registry keys that are made while installing the spellers. Once manually deleted in WinReg, Word starts as it is supposed to.

**Comment by bbqsrc** [comment]
This should no longer be an issue in the most recent version of everything.
